# site.yml
---
#- hosts: srv001
#  become: true
#  roles: []

# docs used as the documentation server
- hosts: docbuild
  become: true
  vars:
    rhbase_ssh_user: msops
    rhbase_ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb3XRQNcl7d4S+/hHMuSp4Xvto7FM81jOnu32ihLvjsmirTGGHwGTe4r+NCXHD8QeM81j6g5y52dvpRvBLVCdDpSLzj1m03RnL8EjJmZM9kQLXX+UfyyC62LYuQkHjZeJ6oTZ0fZ3JKH50kWHUMl9EBSJfyp+nsOfMCRIaRTp+7JxEM+I51mIRLfQognZTPH3n0ZnHIzOU0/YnRb3jo6CJYFJPHAQFNipCDIIMFq+aOyTlp1M9tnijd4t8HwJB5RVHWQwIdQqEtArcJ35/D9v3QM9ehqAC9KuNeRn4kpt2Ba1hj3AYbF2STCmuPQQotIeobsvyV/g6ChoIQarAXjFn msops@catmini.cat9.private'
    rhbase_firewall_allow_services:
      - http
      - https
    rhbase_firewall_allow_ports:
      - 8080/tcp
      - 53/udp
      - 8000/tcp
      - 8090/tcp
      - 8091/tcp
    rhbase_firewall_interfaces:
      - enp0s3
      - enp0s8
    rhbase_start_services:
      - sshd
    rhbase_user_groups:
      - msadmin
      - mstest
    rhbase_users:
      - name: msops
        comment: Administrator
        groups:
          - wheel
          - msadmin
        password: '$6$IljJlWObzDELhyrz$7kK//l0EXs/pt4OUFPKGisgJkbLHPVfw4gxlOqqVHhu.wxYDnfETAhDBBW5pkQiGrNxQ6xKnkKNt4rb85gsCY1'
        #-HINT: defaultmsops
        #-crypt-sha512 https://www.mkpasswd.net/index.php
      - name: cat
        comment: 'Chris A Trees'
        groups:
          - mstest
        password: '$6$eB9rKOzpGYfu0MJJ$58qVMQMltf9WBbTlqDnCZ77fyS371zqsFGJGN3pQ0hbJ7CWHVePy5XkHGFCFXJ2LmezufqrPRvMTKS6g5vgFi1'
        #-HINT: WhatTimeIsIt
        #-crypt-sha512 https://www.mkpasswd.net/index.php
#      - name: confluence
#        comment: 'confluence server user'
#        groups:
#          - confluence
#        password: '$6$IljJlWObzDELhyrz$7kK//l0EXs/pt4OUFPKGisgJkbLHPVfw4gxlOqqVHhu.wxYDnfETAhDBBW5pkQiGrNxQ6xKnkKNt4rb85gsCY1'
        #-HINT: defaultmsops
        #-crypt-sha512 https://www.mkpasswd.net/index.php
    rhbase_selinux_booleans: [httpd_enable_homedirs]
    rhbase_repo_gpgcheck: false
    rhbase_repo_installonly_limit: 2
    rhbase_install_packages: [git, nodejs, java, docker]
# rhbase_install_packages: [git, nodejs, cifs-utils, sphinxcontrib-confluencebuilder]
    rhbase_motd: true
    rhbase_hosts_entry: true
    rhbase_update: true
    rbase_selinux_state: enforcing
    # Setup http site
    httpd_scripting: 'php'
#    httpd_virtualSite: 'msansible.rtd'
#    httpd_users_public_html: ['msops', 'cat']
    # Load the pip documentation packages we use
    pip_package: python-pip
    pip_install_packages:
      - requests
      - Sphinx
#x- sphinxcontrib-confluencebuilder
#x- docker
    # Database for 
#    mariadb_databases:
#      - name: confluence
#      - name: appdb2
#        init_script: files/init_appdb2.sql
#    mariadb_users:
#      - name: confluence
#        password: mailserviceslc
#        priv: 'confluence.*:ALL'
#        host: 'localhost'
#        host: '192.168.56.%'
    # Confluence (these are also defaults put here for refernce)
    # Owner and group for Confluence.
#    confluence_owner: "confluence"
#    confluence_group: "confluence"
    # Location for the $CONFLUENCE_HOME directory.
#    confluence_home: "/var/atlassian/application-data/confluence"
    # Location for the $CONFLUENCE_CATALINA directory.
#    confluence_catalina: "/opt/atlassian/confluence"
    # Confluence Apache Tomcat connector and server port.
#    confluence_connector_port: "8090"
#    confluence_server_port: "8000"
  roles:
    - bertvv.rh-base
    - bertvv.httpd
    - geerlingguy.pip
#x- geerlingguy.docker
#x- bertvv.mariadb
#x- ctrees.confluence
  tasks:
    - name: Enable public_html for users
      template:
        src: docs_userdir.conf.j2
        dest: /etc/httpd/conf.d/userdir.conf
# - name: jack in freakn oracle java cause atlassian sucks
#   shell: 'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm"'
# - name: install the stupid java crap
#   shell: 'yum localinstall jre-8u60-linux-x64.rpm'
# - name: Mount cifs Share
#   mount:
#     state: mounted
#     fstype: cifs
#     name: //freenas.local/shared
#     src: /mnt/freenas
#     opts: "username=msops,password=mailserviceslc,dir_mode=0777,file_mode=0777,uid=0,gid=0,noserverino 0 0"
      # //share/shared /input_files cifs credentials=/home/svc_account/.smbcredentials,dir_mode=0777,file_mode=0777,uid=0,gid=0,noserverino\0400\0400 0 0
  post_tasks:
    - name: Just simple html in /var/www/html
      copy:
        content: |
          </hr></hr><span>This is msansible main http site.</span></hr></hr>
        dest: /var/www/html/index.html
# Pattern from https://www.if-not-true-then-false.com/2010/enable-apache-userdir-with-selinux-on-fedora-centos-red-hat-rhel/
    - name: Set correct perms /home/<user>
      file:
        path: /home/msops
        state: directory
        owner: msops
        group: msops
        mode: 0711
    - name: Create and Set correct perms on /home/user/public_html
      file:
        path: /home/msops/public_html
        state: directory
        owner: msops
        group: msops
        mode: 0755
    - name: Create simple test html
      copy:
        content: |
          </hr></hr><span>This is /home/msops/public_html/index.html test site.</span></hr></hr>
        dest: /home/msops/public_html/index.html
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
# Attempt confluence docker
#    - name: pull confluence docker
#      docker_image:
#        name: atlassian/confluence-server
#    - name: run confluence image
#      docker_container:
#        name: docker-confluence
#        image: atlassian/confluence-server
#        state: started
#        restart: yes
#        published_ports:
#          - 8090:8090
#          - 8091:8091


